#version: '3'
#services:
#  app:
#    build: .
#    ports:
#      - '8080:8080'
#  mongo:
#    image: mongo:4.2.5
#    ports:
#      - '27017:27017'

version: '3.3'
services:
  megandatabase:
    image: mongo:4.2.5
    ports:
      - '27017:27017'
  app:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8080'